### ISSUE TITLE
Could not open input file: apiaxis.php

### ISSUE THREAD

**Issue by madi10** [lycoxz/AxisForTermux#2]
![Screenshot_20220929-123704_Termux.jpg](https://user-images.githubusercontent.com/32736268/192941225-68de5b4c-af61-4964-85f5-009937734064.jpg)

Bang saya ada error seperti gambar di atas, itu cara mengatasinya bagaimana?

Sudah ikutin petunjuk hasil nya nihil.

**Comment by madi10** [comment]
Fix.

Jangan instal atau clone dalam subfolder.

**Comment by lycoxz** [comment]
Monggo di wa saja bro
